[build-system]
# åˆ—å‡ºæ„å»ºç³»ç»Ÿæ‰€éœ€çš„å…¶ä»–å·¥å…·æˆ–åº“
requires = ["setuptools>=61.0"]

# æ„å»ºç³»ç»Ÿçš„åç«¯ï¼Œé€šå¸¸æ˜¯æ„å»ºå·¥å…·çš„åç§°
build-backend = "setuptools.build_meta"


[project]
# é¡¹ç›®çš„åç§°
name = "Expressway"

# é¡¹ç›®çš„ç‰ˆæœ¬å·
version = "1.1.0"

# é¡¹ç›®ä½œè€…çš„ä¿¡æ¯ï¼Œå¯ä»¥åŒ…æ‹¬å§“åå’Œç”µå­é‚®ä»¶åœ°å€
authors = [
  { name="YunhengWang", email="wangyunhenggxy@zjnu.edu.cn" },
]

# é¡¹ç›®çš„ç®€è¦æè¿°
description = "ğŸš€  Expressway network planning ğŸš¦ project in ChongqingğŸ›¤ï¸, Sichuan ProvinceğŸ¼"

# é¡¹ç›®çš„READMEæ–‡ä»¶çš„è·¯å¾„æˆ–URL
readme = "Readme.md"

# é¡¹ç›®æ‰€éœ€çš„Pythonç‰ˆæœ¬
requires-python = ">=3.7"

# é¡¹ç›®çš„åˆ†ç±»ä¿¡æ¯ï¼Œé€šå¸¸ç”¨äºPyPIå‘å¸ƒ
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

# ä¸‹è½½è¯¥åŒ…æ‰€ä¾èµ–çš„ç¬¬ä¸‰æ–¹åº“
dependencies = [
    "networkx~=3.2.1",
    "matplotlib~=3.8.2",
    "tqdm~=4.66.1",
    "geopandas~=0.14.1",
    "scipy~=1.11.4",
    "geopy~=2.4.1",
    "tkinterdnd2~=0.3.0",
    "setuptools~=65.5.1",
    "pandas~=2.1.3",
    "fiona~=1.9.5",
    "shapely~=2.0.2"
]


[project.urls]
"Homepage" = "https://github.com/Yunheng-Wang/Expressway"

"Bug Tracker" = "https://github.com/Yunheng-Wang/Expressway/issues"